# Site Settings
title:               The First Cry of Atom
tagline:             Today is the first day of the rest of my life.
description:
baseurl:            "/"
url:                "https://www.lewuathe.com"
github:
  url:               "https://www.lewuathe.com"
author:
  name:              "Kai Sasaki"
  twitter:           "Lewuathe"
  instagram:         "lewuathe"
  github:            "Lewuathe"
  facebook:          "lewuathe"
  linkedin:          "kaisasaki"
navigation:
- title: About
  url: /about
- title: Writing
  url: /writing
- title: Contact
  url: /contact

paginate:            5
disqus:              #"your-disqus"

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
plugins:                [jekyll-paginate]
